const express = require('express');
const fs = require('fs');
const path = require('path');
const os = require('os');

const app = express();
const PORT = 3737;

const HOME = os.homedir();
const ACCOUNTS_DIR = path.join(HOME, '.claude-accounts');
const BIN_DIR = '/usr/local/bin';
const META_FILE = path.join(ACCOUNTS_DIR, 'accounts.json');

app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// --- Helpers ---

function ensureDirs() {
  fs.mkdirSync(ACCOUNTS_DIR, { recursive: true });
}

function readMeta() {
  const discovered = [];
  if (fs.existsSync(ACCOUNTS_DIR)) {
    for (const entry of fs.readdirSync(ACCOUNTS_DIR, { withFileTypes: true })) {
      if (entry.isDirectory() && !entry.name.startsWith('.')) {
        discovered.push(entry.name);
      }
    }
  }
  let saved = [];
  if (fs.existsSync(META_FILE)) {
    const raw = JSON.parse(fs.readFileSync(META_FILE, 'utf8'));
    saved = Array.isArray(raw.accounts) ? raw.accounts : [];
  }
  const all = [...new Set([...saved, ...discovered])];
  return { accounts: all };
}

function writeMeta(meta) {
  fs.writeFileSync(META_FILE, JSON.stringify(meta, null, 2));
}

function configDir(name) {
  return path.join(ACCOUNTS_DIR, name);
}

function scriptPath(name) {
  return path.join(BIN_DIR, `claude-${name}`);
}

function generateScript(name) {
  const script = `#!/usr/bin/env bash
# Claude CLI wrapper for account: ${name}
# Generated by Claude Account Manager
exec env CLAUDE_CONFIG_DIR="${configDir(name)}" claude "$@"
`;
  const dest = scriptPath(name);
  fs.writeFileSync(dest, script, { mode: 0o755 });
}

function removeScript(name) {
  const p = scriptPath(name);
  if (fs.existsSync(p)) fs.unlinkSync(p);
}

// --- API ---

app.get('/api/accounts', (req, res) => {
  res.json(readMeta());
});

app.post('/api/accounts', (req, res) => {
  const { name } = req.body;
  if (!name || !/^[a-zA-Z0-9_-]+$/.test(name)) {
    return res.status(400).json({ error: 'اسم غير صالح. استخدم حروف، أرقام، - أو _ فقط.' });
  }

  ensureDirs();
  const meta = readMeta();

  if (meta.accounts.includes(name)) {
    return res.status(409).json({ error: 'الحساب موجود مسبقاً.' });
  }

  fs.mkdirSync(configDir(name), { recursive: true });
  meta.accounts.push(name);
  writeMeta(meta);
  generateScript(name);

  res.json({ ok: true, command: `claude-${name}` });
});

app.delete('/api/accounts/:name', (req, res) => {
  const { name } = req.params;
  const meta = readMeta();
  if (!meta.accounts.includes(name)) {
    return res.status(404).json({ error: 'الحساب غير موجود.' });
  }

  const dir = configDir(name);
  if (fs.existsSync(dir)) {
    fs.rmSync(dir, { recursive: true });
  }

  removeScript(name);
  meta.accounts = meta.accounts.filter(a => a !== name);
  writeMeta(meta);

  res.json({ ok: true });
});

// --- UI ---

app.get('/', (req, res) => {
  const lang = req.query.lang || 'ar';
  res.send(renderHTML(readMeta(), lang));
});

function renderHTML(meta, lang) {
  const t = {
    ar: {
      title: 'Claude Account Manager',
      subtitle: 'كل حساب = أمر مستقل في الترمنال',
      addTitle: 'إضافة حساب جديد',
      placeholder: 'اسم الحساب (مثلاً: noor, work)',
      addBtn: 'إضافة',
      copyBtn: 'نسخ الأمر',
      deleteBtn: 'حذف',
      loggedIn: 'مسجّل دخول',
      needsLogin: 'بحاجة تسجيل دخول',
      empty: 'لا توجد حسابات بعد. أضف حسابك الأول!',
      howTitle: 'كيف يشتغل:',
      step1: 'أضف اسم الحساب',
      step2: 'اكتب الأمر في الترمنال:',
      step3: 'سجّل دخول — الجلسة تنحفظ تلقائياً لهذا الحساب فقط',
      step4: 'كل أمر معزول تماماً عن الباقي — لا تداخل أبداً',
      toastAdd: 'تم! استخدم: claude-',
      toastCopy: 'تم نسخ: ',
      toastDelete: 'تم حذف الحساب',
      confirmDelete: 'حذف الحساب ',
      errorEmpty: 'الاسم مطلوب',
      switchLang: 'English',
      switchTo: 'en',
    },
    en: {
      title: 'Claude Account Manager',
      subtitle: 'Each account = independent terminal command',
      addTitle: 'Add New Account',
      placeholder: 'Account name (e.g. noor, work)',
      addBtn: 'Add',
      copyBtn: 'Copy Command',
      deleteBtn: 'Delete',
      loggedIn: 'Logged in',
      needsLogin: 'Needs login',
      empty: 'No accounts yet. Add your first one!',
      howTitle: 'How it works:',
      step1: 'Add an account name',
      step2: 'Type the command in the terminal:',
      step3: 'Log in — the session is saved automatically for this account only',
      step4: 'Each command is fully isolated — no interference',
      toastAdd: 'Done! Use: claude-',
      toastCopy: 'Copied: ',
      toastDelete: 'Account deleted',
      confirmDelete: 'Delete account ',
      errorEmpty: 'Name is required',
      switchLang: 'العربية',
      switchTo: 'ar',
    }
  };
  const s = t[lang] || t.ar;
  const dir = lang === 'ar' ? 'rtl' : 'ltr';
  const htmlLang = lang === 'ar' ? 'ar' : 'en';

  const accountRows = meta.accounts.map(name => {
    const acctDir = configDir(name);
    let hasAuth = false;
    const claudeJson = path.join(acctDir, '.claude.json');
    if (fs.existsSync(claudeJson)) {
      try {
        const data = JSON.parse(fs.readFileSync(claudeJson, 'utf8'));
        hasAuth = !!data.hasCompletedOnboarding;
      } catch(e) {}
    }
    return `
      <div class="account">
        <div class="account-info">
          <span class="account-name">${name}</span>
          <code class="command">claude-${name}</code>
          <span class="status ${hasAuth ? 'logged-in' : 'needs-login'}">${hasAuth ? s.loggedIn : s.needsLogin}</span>
        </div>
        <div class="account-actions">
          <button onclick="copyCmd('claude-${name}')" class="btn btn-copy">${s.copyBtn}</button>
          <button onclick="remove('${name}')" class="btn btn-delete">${s.deleteBtn}</button>
        </div>
      </div>`;
  }).join('');

  return `<!DOCTYPE html>
<html lang="${htmlLang}" dir="${dir}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${s.title}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      background: #0a0a0f;
      color: #e0e0e0;
      min-height: 100vh;
      padding: 2rem;
    }
    .container { max-width: 700px; margin: 0 auto; }
    .top-bar { display: flex; justify-content: flex-end; margin-bottom: 1rem; }
    .lang-btn {
      background: none; border: 1px solid #2a2a3a; color: #c4a35a; padding: 0.3rem 0.8rem;
      border-radius: 8px; cursor: pointer; font-size: 0.8rem; font-weight: 600;
      transition: background 0.2s;
    }
    .lang-btn:hover { background: #14141f; }
    h1 { text-align: center; margin-bottom: 0.5rem; color: #c4a35a; font-size: 1.8rem; }
    .subtitle { text-align: center; color: #888; margin-bottom: 2rem; font-size: 0.9rem; }
    .add-form {
      background: #14141f; border: 1px solid #2a2a3a; border-radius: 12px;
      padding: 1.5rem; margin-bottom: 2rem;
    }
    .add-form h2 { color: #c4a35a; margin-bottom: 1rem; font-size: 1.1rem; }
    .form-row { display: flex; gap: 0.75rem; align-items: center; flex-wrap: wrap; }
    .form-row input[type="text"] {
      flex: 1; min-width: 200px; padding: 0.6rem 1rem; border-radius: 8px;
      border: 1px solid #2a2a3a; background: #0a0a0f; color: #e0e0e0; font-size: 1rem;
    }
    .form-row input:focus { outline: none; border-color: #c4a35a; }
    .btn {
      padding: 0.5rem 1rem; border: none; border-radius: 8px; cursor: pointer;
      font-size: 0.85rem; font-weight: 600; transition: opacity 0.2s;
    }
    .btn:hover { opacity: 0.85; }
    .btn-add { background: #c4a35a; color: #0a0a0f; }
    .btn-copy { background: #2563eb; color: #fff; }
    .btn-delete { background: #dc2626; color: #fff; }
    .accounts-list { display: flex; flex-direction: column; gap: 0.75rem; }
    .account {
      background: #14141f; border: 1px solid #2a2a3a; border-radius: 12px;
      padding: 1rem 1.25rem; display: flex; justify-content: space-between;
      align-items: center; flex-wrap: wrap; gap: 0.75rem;
    }
    .account-info { display: flex; align-items: center; gap: 0.75rem; flex-wrap: wrap; }
    .account-name { font-weight: 700; font-size: 1.1rem; }
    .command {
      display: inline-block; background: #0a0a0f; padding: 0.2rem 0.6rem;
      border-radius: 6px; font-size: 0.8rem; color: #8b8;
    }
    .status { font-size: 0.75rem; padding: 0.15rem 0.5rem; border-radius: 6px; }
    .status.logged-in { background: #16a34a22; color: #4ade80; }
    .status.needs-login { background: #dc262622; color: #f87171; }
    .account-actions { display: flex; gap: 0.5rem; }
    .empty { text-align: center; color: #666; padding: 3rem; font-size: 1.1rem; }
    .how-it-works {
      background: #14141f; border: 1px solid #2a2a3a; border-radius: 12px;
      padding: 1.25rem; margin-top: 2rem; font-size: 0.85rem; color: #888; line-height: 1.9;
    }
    .how-it-works strong { color: #c4a35a; }
    .how-it-works code { background: #0a0a0f; padding: 0.15rem 0.5rem; border-radius: 4px; color: #8b8; }
    .toast {
      position: fixed; bottom: 2rem; left: 50%; transform: translateX(-50%);
      background: #c4a35a; color: #0a0a0f; padding: 0.75rem 1.5rem;
      border-radius: 10px; font-weight: 600; display: none; z-index: 100;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="top-bar">
      <button class="lang-btn" onclick="switchLang()">${s.switchLang}</button>
    </div>
    <h1>${s.title}</h1>
    <p class="subtitle">${s.subtitle}</p>
    <div class="add-form">
      <h2>${s.addTitle}</h2>
      <div class="form-row">
        <input type="text" id="accountName" placeholder="${s.placeholder}" />
        <button class="btn btn-add" onclick="addAccount()">${s.addBtn}</button>
      </div>
    </div>
    <div class="accounts-list">
      ${accountRows || `<div class="empty">${s.empty}</div>`}
    </div>
    <div class="how-it-works">
      <strong>${s.howTitle}</strong><br>
      1. ${s.step1}<br>
      2. ${s.step2} <code>claude-noor</code><br>
      3. ${s.step3}<br>
      4. ${s.step4}
    </div>
  </div>
  <div class="toast" id="toast"></div>
  <script>
    const LANG = "${lang}";
    const STR = ${JSON.stringify(s)};

    function switchLang() {
      window.location.href = '/?lang=' + STR.switchTo;
    }
    function toast(msg) {
      const t = document.getElementById('toast');
      t.textContent = msg;
      t.style.display = 'block';
      setTimeout(() => t.style.display = 'none', 2500);
    }
    async function addAccount() {
      const name = document.getElementById('accountName').value.trim();
      if (!name) return;
      const res = await fetch('/api/accounts', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name })
      });
      const data = await res.json();
      if (res.ok) {
        toast(STR.toastAdd + name);
        setTimeout(() => location.reload(), 800);
      } else {
        toast(data.error);
      }
    }
    function copyCmd(cmd) {
      navigator.clipboard.writeText(cmd).then(() => toast(STR.toastCopy + cmd));
    }
    async function remove(name) {
      if (!confirm(STR.confirmDelete + name + '?')) return;
      const res = await fetch('/api/accounts/' + name, { method: 'DELETE' });
      if (res.ok) {
        toast(STR.toastDelete);
        setTimeout(() => location.reload(), 800);
      }
    }
    document.getElementById('accountName').addEventListener('keydown', e => {
      if (e.key === 'Enter') addAccount();
    });
  </script>
</body>
</html>`;
}

// --- Start ---
ensureDirs();
app.listen(PORT, () => {
  console.log(`\n  Claude Account Manager is running!`);
  console.log(`  http://localhost:${PORT}\n`);
});
